import catchAsyncError from '../middleware/catchAsyncError';

export const signup = catchAsyncError(async (req, res, next) => {});

export const login = catchAsyncError(async (req, res, next) => {});
